Initial commit
panymari/mvc-framework-php pull request #4
Opened 2022-07-08 15:02 UTC by panymari

2022-07-08 20:03 UTC, Melerieko commented on app/Components/Session.php
> +
**Качество кода**: Подобные пробелы излишние, так как чутка страдает красота и качество кода. Не критичное замечание, но лучше так не делать. Это хорошая практика для методов с большим количеством строк, дабы разделять противоположную по смыслу логику. Однако это не совсем подходит для методов с малым количеством строк. (отметил это только здесь, но встречается и дальше по коду)

2022-07-08 20:15 UTC, Melerieko commented on app/Controllers/UserController.php
> +            ['email' => $email, 'name' => $name, 'password' => $password] = $_POST;
**Качество кода**: Впервые вижу подобное описание, чтобы массиву с данными присваивалась переменная `$_POST`. Точно не уверен в валидности подобного написания кода, однако с точки зрения стороннего разработчика, подобная структура выглядит запутанной. Если переменные из массива вытаскиваются из `$_POST` (что подходит по логике), тогда данная строчка добавляет неразберихи в код. Однако если эта строчка вносит данные по кредам пользователя в переменную `$_POST`, то это тоже есть не хорошо, так как POST-переменные - есть POST-переменные. Их нужно только использовать в последующем функционале, но никак не закидывать в них доп. данные. Нужно уточнение по логике написания данной строчки. Не критично, но требуются разъяснения.

2022-07-08 20:42 UTC, Melerieko commented on app/Models/User.php
> +        $sql = 'INSERT INTO users (email, name, password) VALUES (:email, :name, :password)';
**Совсем не критичное замечание. Совет**: В данной таске используются данные пользователя из сидов. Я вижу, что пароль пользователя хэшируется прямо в сидах, однако лучше бы его хэшировать прямо тут, при отправке в базу. Так как в дальнейшем (при выполнении таски с регистрацией), пароль по-хорошему надо хэшировать тут. Сподручнее создать переменную с хэшем пароля (можно не так, но как-нибудь похоже), а затем передать хэшированный пароль в SQL-запрос.

2022-07-11 07:40 UTC, nashalda requested changes

2022-07-11 07:40 UTC, nashalda commented on app/Models/User.php
> +        $sql = 'INSERT INTO users (email, name, password) VALUES (:email, :name, :password)';
+++

2022-07-11 07:40 UTC, nashalda commented on app/Components/Session.php
> +        session_destroy();
session_destroy(); - не стоит

2022-07-11 07:40 UTC, nashalda commented on config/const.php
> +const VIEW_ROOT_USERS = ROOT . '/views/authentication/'; // folder with authentication views
VIEW_ROOT_USERS -

2022-07-11 11:27 UTC, Melerieko approved these changes

2022-07-12 07:28 UTC, merged