File uploader application
panymari/mvc-framework-php pull request #6
Opened 2022-07-14 08:58 UTC by panymari

2022-07-14 11:00 UTC, Melerieko commented on file-uploader-application/app/Controllers/FileController.php
> +            $file_loc = $_FILES['file']['tmp_name'];
Lower snake переделать под Camel Case

2022-07-14 13:26 UTC, Melerieko commented
Таскана проверена. Все замечания донесены словесно. Все исправления просмотрены и одобрены. По работе программы нареканий нет. Можно мержить

2022-07-14 13:56 UTC, Melerieko commented
Таскана проверена. Все замечания донесены словесно. Все исправления просмотрены и одобрены. По работе программы нареканий нет. Можно мержить

2022-07-15 09:30 UTC, nashalda requested changes

2022-07-15 09:30 UTC, nashalda commented on file-uploader-application/app/Controllers/UserController.php
> +                        $weekToSec = 604800;
2 раза поворяется по коду - вынеси в константу класса

2022-07-15 09:30 UTC, nashalda commented on file-uploader-application/app/Controllers/FileController.php
> +<?php
файл сессий составлен некорректно - смотри замечания прошлоги таска

2022-07-15 09:30 UTC, nashalda commented on file-uploader-application/app/Controllers/UserController.php
> +        $last = 900 - $diff;
900 тоже в константы, так как непонятно что происходит в этой строке

2022-07-15 09:30 UTC, nashalda commented on file-uploader-application/app/Controllers/UserController.php
> +                Session::delete('locked_time');
Если пишешь свой метод SESSION, то научи его удалять массивы параметров

2022-07-15 09:30 UTC, nashalda commented on file-uploader-application/app/Controllers/FileController.php
> +            $file = rand(1000, 100000) . "-" . $_FILES['file']['name']; //give a unique name to each file
для генерациии уникального имени файла используем uniqid();

2022-07-15 09:30 UTC, nashalda commented on file-uploader-application/app/Controllers/UserController.php
> +        Session::start();
огромный метод. его надо разделить на несколько отдельных, кажддый из которых будет выполнять что-то одно - isUserLocked, getAttempts, checkUserCredentials ит.д.

2022-07-25 10:03 UTC, merged